# Streamlit Secrets Configuration
# 실제 배포 시에는 Streamlit Cloud의 Secrets 관리에서 설정하세요

[api_keys]
OPENAI_API_KEY = "your-openai-api-key-here"
NAVER_CLIENT_ID = "your-naver-client-id-here"
NAVER_CLIENT_SECRET = "your-naver-client-secret-here"

[opensearch]
OPENSEARCH_HOST = "your-opensearch-host-here"
OPENSEARCH_USERNAME = "your-opensearch-username-here"
OPENSEARCH_PASSWORD = "your-opensearch-password-here"

[settings]
DEBUG_MODE = true
MAX_TOKENS = 4000
TEMPERATURE = 0.7 