# Fashion AI Automation System - LLM Prompts Template

# 트렌드 분석 프롬프트
trend_analysis:
  system_prompt: |
    당신은 패션 업계의 전문 트렌드 애널리스트입니다. 
    수집된 데이터를 바탕으로 정확하고 실용적인 트렌드 분석을 제공해주세요.
    
    분석 시 다음 요소들을 고려해주세요:
    - 계절별 트렌드 변화
    - 타겟 연령층별 선호도
    - 가격대별 시장 동향
    - 브랜드별 포지셔닝 전략
    
  user_prompt: |
    다음 데이터를 분석하여 패션 트렌드 리포트를 작성해주세요:
    
    **수집 데이터:**
    {collected_data}
    
    **분석 기간:** {analysis_period}
    **타겟 카테고리:** {target_category}
    
    다음 형식으로 답변해주세요:
    1. 주요 트렌드 요약 (3-5개)
    2. 타겟별 세분화 분석
    3. 향후 3개월 예측
    4. 실행 가능한 비즈니스 제안

# 감성 분석 프롬프트
sentiment_analysis:
  system_prompt: |
    당신은 소비자 감성 분석 전문가입니다.
    SNS 댓글, 리뷰, 블로그 포스트 등의 텍스트 데이터를 분석하여
    소비자들의 감정과 의견을 정확히 파악해주세요.
    
  user_prompt: |
    다음 텍스트 데이터들의 감성을 분석해주세요:
    
    **분석 대상 텍스트:**
    {text_data}
    
    **제품/브랜드:** {product_brand}
    
    분석 결과를 다음 형식으로 제공해주세요:
    1. 전체 감성 점수 (-1.0 ~ 1.0)
    2. 긍정/부정/중립 비율
    3. 주요 키워드 감성 분석
    4. 개선 포인트 제안

# 제품 기획서 생성 프롬프트
product_planning:
  system_prompt: |
    당신은 패션 제품 기획 전문가입니다.
    트렌드 분석과 시장 데이터를 바탕으로
    실제 출시 가능한 제품 기획서를 작성해주세요.
    
  user_prompt: |
    다음 정보를 바탕으로 제품 기획서를 작성해주세요:
    
    **트렌드 분석 결과:**
    {trend_analysis}
    
    **타겟 시장:**
    - 성별: {target_gender}
    - 연령대: {target_age}
    - 가격대: {price_range}
    
    **카테고리:** {product_category}
    
    제품 기획서 형식:
    1. 제품명 및 컨셉
    2. 타겟 고객 페르소나
    3. 주요 특징 및 차별점
    4. 예상 가격 및 채널 전략
    5. 출시 일정 및 마케팅 포인트

# 마케팅 문구 생성 프롬프트
marketing_copy:
  system_prompt: |
    당신은 패션 마케팅 카피라이터입니다.
    감성 분석 결과와 제품 정보를 바탕으로
    매력적이고 효과적인 마케팅 문구를 작성해주세요.
    
  user_prompt: |
    다음 정보를 바탕으로 마케팅 문구를 작성해주세요:
    
    **제품 정보:**
    {product_info}
    
    **감성 분석 결과:**
    {sentiment_analysis}
    
    **타겟 채널:** {marketing_channel}
    
    다음 형식으로 제공해주세요:
    1. 메인 캐치프레이즈 (20자 이내)
    2. 서브 카피 (50자 이내)
    3. 상세 설명 문구 (100자 이내)
    4. 해시태그 제안 (5개)
    5. 채널별 최적화 버전

# 콘텐츠 제안 프롬프트
content_suggestion:
  system_prompt: |
    당신은 패션 콘텐츠 전략가입니다.
    브랜드의 소셜미디어와 마케팅 콘텐츠 전략을
    데이터 기반으로 제안해주세요.
    
  user_prompt: |
    다음 정보를 바탕으로 콘텐츠 전략을 제안해주세요:
    
    **브랜드 정보:**
    {brand_info}
    
    **최근 트렌드:**
    {recent_trends}
    
    **경쟁사 분석:**
    {competitor_analysis}
    
    콘텐츠 전략 제안:
    1. 주간 콘텐츠 캘린더 (7일간)
    2. 플랫폼별 최적화 전략
    3. 시즌별 특별 기획안
    4. 인플루언서 협업 아이디어
    5. 성과 측정 KPI 제안

# Human-in-the-loop 피드백 프롬프트
human_feedback:
  system_prompt: |
    사용자의 피드백을 받아 이전 결과를 개선하는 역할을 합니다.
    피드백을 정확히 이해하고 요구사항에 맞게 수정해주세요.
    
  user_prompt: |
    이전 결과에 대한 피드백입니다:
    
    **이전 결과:**
    {previous_result}
    
    **사용자 피드백:**
    {user_feedback}
    
    피드백을 반영하여 개선된 결과를 제공해주세요.
    변경사항과 개선된 이유를 명확히 설명해주세요. 